#VIEWS
default_view:
    view: yes
    icon: mdi:home-assistant
    entities:
      - group.soverom
      - group.opphalds_varme
      - group.bad
      - group.alarm_clock
      - group.sporing

light:
  name: Lys
  icon: mdi:lightbulb
  view: yes
  entities:
    - group.rom
    - group.soverom_lys
    - group.tak
    - group.pult
    - group.tv
    - group.kitchen
    - group.bad_brytar
    - group.scener

doors:
  name: Dører
  icon: mdi:door
  view: yes
  entities:
    - group.door_group
    - group.door_status
    - group.seng
    - group.rorsle

sonos:
  name: Sonos
  icon: mdi:speaker
  view: yes
  entities:
    - media_player.opphaldsrom 
    - media_player.kontor
    - media_player.soverom
    - media_player.bad
    - media_player.living_room_speaker 
    - media_player.tv

klima:
  name: Klima
  icon: mdi:thermometer
  view: yes
  entities:
    - group.netatmo_inne
    - group.netatmo_ute
    - group.soverom_temp
    - group.bad_temp
    - group.vaer
    - group.flower_sensor_1
    - group.flower_sensor_2
    - group.nest

System:
    name: System
    icon: mdi:settings
    view: yes
    entities:
      - updater.updater
      - group.system_group
      - group.speedtest
      - light.gateway_light_34ce00909f02
      - group.all_scripts
      - script.co2_level
      - script.out_temp
      - sensor.social_blade
      - group.straum


automation:
    name: Automasjonar
    icon: mdi:robot
    view: yes
    entities:
      - group.auto_alarm_clock
      - group.auto_arriving_home
      - group.auto_audio
      - group.auto_away_mode
      - group.auto_bathroom
      - group.auto_bed
      - group.auto_heating
      - group.auto_ipad_notification
      - group.auto_lights
      - group.auto_lock
      - group.auto_plant_alert
      - group.auto_tv

Test:
  name: Test
  view: yes
  entities:
    - switch.flux 
    - switch.test
    
    
    

