- alias: Double Click to toggle Peter nightstand
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001870d6f
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.nattbord_peter

- alias: Single Click to toggle Peter nightstand
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001870d6f
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.nattbord_natalia

- alias: Long Press to toggle bedroom lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001870d6f
      click_type: long_click_press
  action:
    service: light.toggle
    data:
      entity_id: light.soverom_2

- alias: Someone is in bed
  trigger:
    platform: state
    entity_id: binary_sensor.bed_sensor
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'device_tracker.pixel2xl'
        state: 'home'
      - condition: state
        entity_id: 'device_tracker.pixel_2_xl'
        state: 'home'
      - condition: time
        after: '22:00:00'
        before: '08:00:00'
      - condition: state
        entity_id: light.nattbord_peter
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.light
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('light.nattbord_peter', 'off') %}
            scene.nattlys_peter
          {% else %}
          {% endif %}
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.bad
        - media_player.kontor
        - media_player.opphaldsrom
      






      