- alias: Charge iPad notification
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    - condition: state
      entity_id: device_tracker.pixel2xl
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.battery_ipad
      below: 45
  action:
    - service: notify.notifier_html_peter_unnamed_device_3
      data:
        title: "Lad iPaden"
        message: "Hugs å lade iPaden før skule i morgon!"
        target: "unnamed device 3"
